export const REQUEST_TOP_PENDING = 'REQUEST_TOP_PENDING';
export const REQUEST_TOP_SUCCESS = 'REQUEST_TOP_SUCCESS';
export const REQUEST_TOP_FAILED = 'REQUEST_TOP_FAILED';

export const REQUEST_POPULAR_PENDING = 'REQUEST_POPULAR_PENDING';
export const REQUEST_POPULAR_SUCCESS = 'REQUEST_POPULAR_SUCCESS';
export const REQUEST_POPULAR_FAILED = 'REQUEST_POPULAR_FAILED';