export const REQUEST_TOP_PENDING = 'REQUEST_TOP_PENDING';
export const REQUEST_TOP_SUCCESS = 'REQUEST_TOP_SUCCESS';
export const REQUEST_TOP_FAILED = 'REQUEST_TOP_FAILED';

export const REQUEST_POPULAR_PENDING = 'REQUEST_POPULAR_PENDING';
export const REQUEST_POPULAR_SUCCESS = 'REQUEST_POPULAR_SUCCESS';
export const REQUEST_POPULAR_FAILED = 'REQUEST_POPULAR_FAILED';

export const REQUEST_LATEST_PENDING = 'REQUEST_LATEST_PENDING';
export const REQUEST_LATEST_SUCCESS = 'REQUEST_LATEST_SUCCESS';
export const REQUEST_LATEST_FAILED = 'REQUEST_LATEST_FAILED';


export const REQUEST_THEATRES_PENDING = 'REQUEST_THEATRES_PENDING';
export const REQUEST_THEATRES_SUCCESS = 'REQUEST_THEATRES_SUCCESS';
export const REQUEST_THEATRES_FAILED = 'REQUEST_THEATRES_FAILED';

